server:
  port: 8095

spring:
  application:
    name: msvc-yanki
  data:
    mongodb:
      uri: mongodb://localhost:27017/yankis

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka