eureka:
  client:
    register-with-eureka: false

server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes[0]:
          id: microservice-client
          uri: lb://msvc-client
          predicates[0]:
            Path=/clients/**
