server:
  port: 8094

spring:
  application:
    name: msvc-card
  data:
    mongodb:
      uri: mongodb://localhost:27017/cards

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka